# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/wrongsecrets-balancer/" # Location of package manifests
    open-pull-requests-limit: 15
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/wrongsecrets-balancer/ui" # Location of package manifests
    open-pull-requests-limit: 16
    schedule:
      interval: "monthly"
    # check our npm for dev
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/cleaner" # Location of package manifests
    open-pull-requests-limit: 15
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/wrongsecrets-balancer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/azure"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/gcp"
    schedule:
      interval: "monthly"
